#!/bin/bash
# Hướng dẫn sử dụng:
# Chạy script này từ thư mục gốc của dự án: ./package_arch.sh
set -e

PKGVER="1.0.4"
PKGREL="1"
# Tự động phát hiện kiến trúc hệ thống
DETECTED_ARCH=$(uname -m)
if command -v dpkg &> /dev/null; then
    DEB_ARCH=$(dpkg --print-architecture)
    if [ "$DEB_ARCH" = "arm64" ]; then
        DETECTED_ARCH="aarch64"
    elif [ "$DEB_ARCH" = "amd64" ]; then
        DETECTED_ARCH="x86_64"
    fi
fi

if [ "$DETECTED_ARCH" = "x86_64" ] || [ "$DETECTED_ARCH" = "amd64" ]; then
    ARCH="x86_64"
elif [ "$DETECTED_ARCH" = "aarch64" ] || [ "$DETECTED_ARCH" = "arm64" ]; then
    ARCH="aarch64"
else
    ARCH="$DETECTED_ARCH"
fi
PKGNAME="unikey-wayland"
FULL_PKGVER="${PKGVER}-${PKGREL}"
PKG_OUTPUT="releases/${PKGNAME}-${FULL_PKGVER}-${ARCH}.pkg.tar.zst"

echo ">>> Bắt đầu đóng gói Arch Linux (tar.zst) cho ${PKGNAME} ${FULL_PKGVER}"

# 1. Kiểm tra môi trường
if ! command -v bsdtar &> /dev/null; then
    echo "Lỗi: Công cụ 'bsdtar' không tồn tại trên hệ thống."
    echo "Vui lòng cài đặt libarchive (bsdtar) trước khi tiếp tục."
    exit 1
fi

if [ ! -f "wayland-client/build/unikey-wayland" ]; then
    echo "Lỗi: Không tìm thấy file nhị phân."
    echo "Vui lòng build mã nguồn trước (thư mục wayland-client/build/unikey-wayland)."
    exit 1
fi

# 2. Tạo cấu trúc thư mục
echo ">>> Tạo cấu trúc thư mục..."
rm -rf arch_pkg
mkdir -p releases
mkdir -p arch_pkg/usr/bin
mkdir -p arch_pkg/usr/share/applications
mkdir -p arch_pkg/usr/share/metainfo

# 3. Sao chép các tệp tin cấu hình và binary
echo ">>> Đang sao chép các tệp tin hệ thống..."
cp wayland-client/build/unikey-wayland arch_pkg/usr/bin/
cp unikey-wayland.desktop arch_pkg/usr/share/applications/
cp unikey-wayland.metainfo.xml arch_pkg/usr/share/metainfo/

# 4. Thay đổi quyền truy cập tiêu chuẩn
chmod 755 arch_pkg/usr/bin/unikey-wayland
chmod 644 arch_pkg/usr/share/applications/unikey-wayland.desktop
chmod 644 arch_pkg/usr/share/metainfo/unikey-wayland.metainfo.xml

# 5. Lấy kích thước cài đặt thực tế (bytes)
SIZE=$(du -sb arch_pkg/usr | cut -f1)
BUILD_DATE=$(date +%s)

# 6. Tạo file thông tin mô tả đặc tả (Metadata của Arch Linux)
echo ">>> Tạo file metadata (.PKGINFO)..."
cat <<EOF > arch_pkg/.PKGINFO
# Generated by package_arch.sh script
pkgname = ${PKGNAME}
pkgbase = ${PKGNAME}
xdata = pkgtype=pkg
pkgver = ${FULL_PKGVER}
pkgdesc = Unikey Wayland Input Method for Vietnamese
url = https://github.com/ubuntu2310fake/Unikey-Wayland
builddate = ${BUILD_DATE}
packager = truonghieu
size = ${SIZE}
arch = ${ARCH}
license = GPL-3.0-or-later
depend = qt6-base
depend = wayland
EOF

# Tạo file INSTALL rỗng
touch arch_pkg/.INSTALL

chmod 644 arch_pkg/.PKGINFO
chmod 644 arch_pkg/.INSTALL

# 7. Đóng gói chuẩn bằng công cụ bsdtar (Loại bỏ triệt để tiền tố ./)
echo ">>> Nén thành định dạng gói ${PKG_OUTPUT}..."
bsdtar --zstd -cf "${PKG_OUTPUT}" -C arch_pkg .PKGINFO .INSTALL usr

# 8. Dọn dẹp
rm -rf arch_pkg

echo ">>> Hoàn tất! Tệp tin đã sẵn sàng tại: ${PKG_OUTPUT}"
