#!/bin/bash
# Hướng dẫn sử dụng:
# Chạy script này từ thư mục gốc của dự án: ./package_arch.sh
set -e

PKGVER="3.0.2"
PKGREL="1"
# Tự động phát hiện kiến trúc hệ thống
DETECTED_ARCH=$(uname -m)
if command -v dpkg &> /dev/null; then
    DEB_ARCH=$(dpkg --print-architecture)
    if [ "$DEB_ARCH" = "arm64" ]; then
        DETECTED_ARCH="aarch64"
    elif [ "$DEB_ARCH" = "amd64" ]; then
        DETECTED_ARCH="x86_64"
    fi
fi

if [ "$DETECTED_ARCH" = "x86_64" ] || [ "$DETECTED_ARCH" = "amd64" ]; then
    ARCH="x86_64"
elif [ "$DETECTED_ARCH" = "aarch64" ] || [ "$DETECTED_ARCH" = "arm64" ]; then
    ARCH="aarch64"
else
    ARCH="$DETECTED_ARCH"
fi
PKGNAME="unikey-wayland"
FULL_PKGVER="3.0.2"
PKG_OUTPUT="releases/${PKGNAME}-${FULL_PKGVER}-${ARCH}.pkg.tar.zst"

echo ">>> Bắt đầu đóng gói Arch Linux (tar.zst) cho ${PKGNAME} ${FULL_PKGVER}"

# 1. Kiểm tra môi trường
if ! command -v bsdtar &> /dev/null; then
    echo "Lỗi: Công cụ 'bsdtar' không tồn tại trên hệ thống."
    echo "Vui lòng cài đặt libarchive (bsdtar) trước khi tiếp tục."
    exit 1
fi

if [ ! -f "wayland-client/build/unikey-wayland" ]; then
    echo "Lỗi: Không tìm thấy file nhị phân."
    echo "Vui lòng build mã nguồn trước (thư mục wayland-client/build/unikey-wayland)."
    exit 1
fi

# 2. Tạo cấu trúc thư mục
echo ">>> Tạo cấu trúc thư mục..."
rm -rf arch_pkg
mkdir -p releases
mkdir -p arch_pkg/usr/bin
mkdir -p arch_pkg/usr/libexec
mkdir -p arch_pkg/usr/src/ukw-driver-1.0
mkdir -p arch_pkg/usr/lib/systemd/system
mkdir -p arch_pkg/usr/share/X11/xkb/symbols
mkdir -p arch_pkg/usr/share/ibus/component
mkdir -p arch_pkg/usr/share/applications
mkdir -p arch_pkg/usr/share/metainfo
mkdir -p arch_pkg/usr/share/icons/hicolor/scalable/apps

# 3. Sao chép các tệp tin cấu hình và binary
echo ">>> Đang sao chép các tệp tin hệ thống..."
cp wayland-client/build/unikey-wayland arch_pkg/usr/bin/
if [ -f wayland-client/build/ibus-engine-unikey-wayland ]; then
    cp wayland-client/build/ibus-engine-unikey-wayland arch_pkg/usr/libexec/
fi
if [ -f ibus-engine/unikey-wayland.xml ]; then
    cp ibus-engine/unikey-wayland.xml arch_pkg/usr/share/ibus/component/
fi
if [ -f ibus-engine/ibus-setup-unikey-wayland.desktop ]; then
    cp ibus-engine/ibus-setup-unikey-wayland.desktop arch_pkg/usr/share/applications/
fi
cp io.github.ubuntu2310fake.UnikeyWayland.desktop arch_pkg/usr/share/applications/
cp io.github.ubuntu2310fake.UnikeyWayland.metainfo.xml arch_pkg/usr/share/metainfo/
cp io.github.ubuntu2310fake.UnikeyWayland.svg arch_pkg/usr/share/icons/hicolor/scalable/apps/

# 4. Thay đổi quyền truy cập tiêu chuẩn
# Copy Ring-0 components
cp wayland-client/build/ukw_daemon arch_pkg/usr/bin/
cp ring0-engine/dkms.conf arch_pkg/usr/src/ukw-driver-1.0/
cp ring0-engine/Makefile arch_pkg/usr/src/ukw-driver-1.0/
cp ring0-engine/ukw_driver.c arch_pkg/usr/src/ukw-driver-1.0/
cp ring0-engine/ukw.service arch_pkg/usr/lib/systemd/system/
mkdir -p arch_pkg/usr/lib/modules-load.d
cp ring0-engine/ukw.conf arch_pkg/usr/lib/modules-load.d/
mkdir -p arch_pkg/usr/share/unikey-wayland
cp ring0-engine/xkb/ukw arch_pkg/usr/share/unikey-wayland/ukw_xkb

chmod 755 arch_pkg/usr/bin/unikey-wayland
chmod 755 arch_pkg/usr/bin/ukw_daemon
if [ -f arch_pkg/usr/libexec/ibus-engine-unikey-wayland ]; then
    chmod 755 arch_pkg/usr/libexec/ibus-engine-unikey-wayland
fi
if [ -f arch_pkg/usr/share/ibus/component/unikey-wayland.xml ]; then
    chmod 644 arch_pkg/usr/share/ibus/component/unikey-wayland.xml
fi
if [ -f arch_pkg/usr/share/applications/ibus-setup-unikey-wayland.desktop ]; then
    chmod 644 arch_pkg/usr/share/applications/ibus-setup-unikey-wayland.desktop
fi
chmod 644 arch_pkg/usr/share/applications/io.github.ubuntu2310fake.UnikeyWayland.desktop
chmod 644 arch_pkg/usr/share/metainfo/io.github.ubuntu2310fake.UnikeyWayland.metainfo.xml
chmod 644 arch_pkg/usr/share/icons/hicolor/scalable/apps/io.github.ubuntu2310fake.UnikeyWayland.svg

# 5. Lấy kích thước cài đặt thực tế (bytes)
SIZE=$(du -sb arch_pkg/usr | cut -f1)
BUILD_DATE=$(date +%s)

# 6. Tạo file thông tin mô tả đặc tả (Metadata của Arch Linux)
echo ">>> Tạo file metadata (.PKGINFO)..."
cat <<EOF > arch_pkg/.PKGINFO
# Generated by package_arch.sh script
pkgname = ${PKGNAME}
pkgbase = ${PKGNAME}
xdata = pkgtype=pkg
pkgver = ${FULL_PKGVER}
pkgdesc = Unikey Wayland Input Method for Vietnamese
url = https://github.com/ubuntu2310fake/Unikey-Wayland
builddate = ${BUILD_DATE}
packager = truonghieu
size = ${SIZE}
arch = ${ARCH}
license = GPL-3.0-or-later
depend = qt6-base
depend = wayland
depend = dkms
EOF

# Tạo file INSTALL rỗng
cat <<'INSTALL_EOF' > arch_pkg/.INSTALL
post_install() {
    cp /usr/share/unikey-wayland/ukw_xkb /usr/share/X11/xkb/symbols/ukw 2>/dev/null || true
    if command -v dkms >/dev/null 2>&1; then
        dkms add -m ukw-driver -v 1.0 || true
        dkms build -m ukw-driver -v 1.0 || true
        dkms install -m ukw-driver -v 1.0 || true
    fi
    systemctl daemon-reload || true
    systemctl enable ukw.service || true
    systemctl restart ukw.service || true
}

pre_remove() {
    systemctl stop ukw.service || true
    systemctl disable ukw.service || true
    if command -v dkms >/dev/null 2>&1; then
        dkms remove -m ukw-driver -v 1.0 --all || true
    fi
}

post_remove() {
    rm -f /usr/share/X11/xkb/symbols/ukw
}
INSTALL_EOF


chmod 644 arch_pkg/.PKGINFO
chmod 644 arch_pkg/.INSTALL

# 7. Đóng gói chuẩn bằng công cụ bsdtar (Loại bỏ triệt để tiền tố ./)
echo ">>> Nén thành định dạng gói ${PKG_OUTPUT}..."
bsdtar --zstd -cf "${PKG_OUTPUT}" -C arch_pkg .PKGINFO .INSTALL usr

# 8. Dọn dẹp
rm -rf arch_pkg

echo ">>> Hoàn tất! Tệp tin đã sẵn sàng tại: ${PKG_OUTPUT}"
